'use client'

import { useState, useEffect, useMemo } from 'react'
import {
  PlusCircle,
  Loader2,
  Ticket,
  Pencil,
  Trash,
  Trash2,
  Percent,
  IndianRupee,
  ToggleRight,
  ToggleLeft,
  X,
  Sparkles,
  Flame,
  Truck,
  Store,
  Gift,
  CheckCircle2,
} from 'lucide-react'
import { formatDate } from '@/lib/date-helpers'
import { toast } from 'sonner'
import { cn } from '@/lib/utils'

interface Category {
  id: string
  name: string
}

interface Coupon {
  id: string
  code: string
  discountType: string
  bogoType?: string | null
  triggerVariant?: string | null
  rewardVariant?: string | null
  badgeText?: string | null
  autoApply?: boolean
  value: number
  minOrder: number | string
  maxDiscount: number | string | null
  maxUses: number | string | null
  expiresAt: string | null
  isActive: boolean
  categoryId: string | null
  restaurantId?: string | null
  restaurant?: { id: string; name: string; slug: string } | null
  menuSection?: string | null
  oncePerCustomer: boolean
  usedCount: number
}

interface CouponEditForm {
  code: string
  discountType: string
  bogoType?: string
  triggerVariant?: string
  rewardVariant?: string
  restaurantId?: string
  menuSection?: string
  badgeText?: string
  autoApply?: boolean
  syncRestaurantBadge?: boolean
  value: string
  minOrder: string
  maxDiscount: string
  maxUses: string
  expiresAt: string
  isActive: boolean
  categoryId: string
  oncePerCustomer: boolean
}

interface CouponsTabProps {
  coupons: Coupon[]
  categories: Category[]
  showAddCoupon: boolean
  isCreatingCoupon: boolean
  isLoadingCoupons: boolean
  savingCouponId: string | null
  deletingCouponId: string | null
  newCoupon: CouponEditForm
  editingCoupon: Coupon | null
  couponEditForm: CouponEditForm
  setShowAddCoupon: (v: boolean) => void
  setNewCoupon: (v: any) => void
  setEditingCoupon: (c: Coupon | null) => void
  setCouponEditForm: (v: any) => void
  handleCreateCoupon: (e: React.FormEvent) => Promise<void>
  saveCouponChanges: (e: React.FormEvent) => Promise<void>
  handleToggleCoupon: (couponId: string, currentActive: boolean) => Promise<void>
  handleDeleteCoupon: (couponId: string) => Promise<void>
  startEditingCoupon: (c: Coupon) => void
}

export function CouponsTab({
  coupons,
  categories,
  showAddCoupon,
  isCreatingCoupon,
  isLoadingCoupons,
  savingCouponId,
  deletingCouponId,
  newCoupon,
  editingCoupon,
  couponEditForm,
  setShowAddCoupon,
  setNewCoupon,
  setEditingCoupon,
  setCouponEditForm,
  handleCreateCoupon,
  saveCouponChanges,
  handleToggleCoupon,
  handleDeleteCoupon,
  startEditingCoupon,
}: CouponsTabProps) {
  const [restaurants, setRestaurants] = useState<Array<{ id: string; name: string; slug: string; menuSections?: any }>>([])
  const [previewTab, setPreviewTab] = useState<'card' | 'menu' | 'cart'>('card')

  useEffect(() => {
    fetch('/api/restaurants?all=true')
      .then((res) => res.json())
      .then((data) => {
        if (Array.isArray(data)) {
          setRestaurants(data)
        }
      })
      .catch((err) => console.warn('Failed to load restaurants for coupons tab:', err))
  }, [])

  const getRestaurantMenuSections = (rest: any) => {
    if (!rest || !rest.menuSections) return []
    try {
      const raw = typeof rest.menuSections === 'string' ? JSON.parse(rest.menuSections) : rest.menuSections
      if (Array.isArray(raw)) {
        return raw
          .map((s: any) => ({
            tag: s.tag || s.title?.toLowerCase().replace(/[^a-z0-9]/g, '') || '',
            title: s.title || s.tag || '',
          }))
          .filter((s: any) => !!s.tag)
      }
    } catch {}
    return []
  }

  // Auto-generate suggested badge text based on inputs
  const autoGeneratedBadge = useMemo(() => {
    if (newCoupon.discountType === 'BOGO') {
      if (newCoupon.bogoType === 'BUY_LARGE_GET_SMALL') {
        const trig = (newCoupon.triggerVariant || 'Large').toUpperCase()
        const rew = (newCoupon.rewardVariant || 'Small').toUpperCase()
        const sec = newCoupon.menuSection ? ` ${newCoupon.menuSection.toUpperCase()}` : ''
        return `BUY ${trig}${sec} GET ${rew} FREE`
      }
      if (newCoupon.bogoType === 'CHEAPEST_FREE') {
        return 'BUY ANY 2, CHEAPEST FREE'
      }
      return 'BUY 1 GET 1 FREE'
    }
    if (newCoupon.discountType === 'FREE_DELIVERY') {
      return 'FREE DELIVERY'
    }
    if (newCoupon.discountType === 'PERCENT') {
      return `${newCoupon.value || '20'}% OFF`
    }
    if (newCoupon.discountType === 'FLAT') {
      return `FLAT ₹${newCoupon.value || '50'} OFF`
    }
    return 'EXCLUSIVE OFFER'
  }, [newCoupon.discountType, newCoupon.bogoType, newCoupon.triggerVariant, newCoupon.rewardVariant, newCoupon.menuSection, newCoupon.value])

  const selectedRestaurant = restaurants.find((r) => r.id === newCoupon.restaurantId)
  const effectiveBadge = newCoupon.badgeText?.trim() || autoGeneratedBadge

  // Stats
  const activeCoupons = coupons.filter((c) => c.isActive)
  const bogoCoupons = coupons.filter((c) => c.discountType === 'BOGO' && c.isActive)
  const restaurantCoupons = coupons.filter((c) => c.restaurantId && c.isActive)

  return (
    <div className="space-y-6">
      {/* Header with KPI cards */}
      <div className="flex flex-col md:flex-row gap-4 items-start md:items-center justify-between">
        <div>
          <div className="flex items-center gap-2">
            <h3 className="font-extrabold text-text-primary text-base sm:text-lg">
              Promotion &amp; Offer Studio
            </h3>
            <span className="px-2 py-0.5 rounded-md bg-gradient-to-r from-orange-500 to-red-500 text-[10px] font-black text-white uppercase tracking-wider shadow-xs">
              Live Engine
            </span>
          </div>
          <p className="text-xs text-text-secondary mt-0.5">
            Launch BOGO deals, variant promotions, restaurant coupons &amp; automatic cart gifts
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={() => setShowAddCoupon(!showAddCoupon)}
            className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-orange-600 to-red-600 hover:from-orange-700 hover:to-red-700 text-white text-xs font-black rounded-xl shadow-md transition-all active:scale-95 cursor-pointer"
          >
            {showAddCoupon ? <X className="h-4 w-4" /> : <PlusCircle className="h-4 w-4" />}
            <span>{showAddCoupon ? 'Close Creator' : 'Create Campaign'}</span>
          </button>
        </div>
      </div>

      {/* KPI strip */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="p-3.5 rounded-2xl bg-card border border-border shadow-2xs">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-bold text-text-muted uppercase tracking-wider">Active Deals</span>
            <Ticket className="w-4 h-4 text-purple-500" />
          </div>
          <p className="text-lg font-black text-text-primary mt-1">
            {activeCoupons.length} <span className="text-xs font-normal text-text-muted">/ {coupons.length}</span>
          </p>
        </div>

        <div className="p-3.5 rounded-2xl bg-card border border-border shadow-2xs">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-bold text-text-muted uppercase tracking-wider">BOGO Offers</span>
            <Flame className="w-4 h-4 text-orange-500" />
          </div>
          <p className="text-lg font-black text-orange-600 mt-1">
            {bogoCoupons.length} <span className="text-xs font-normal text-text-muted">active</span>
          </p>
        </div>

        <div className="p-3.5 rounded-2xl bg-card border border-border shadow-2xs">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-bold text-text-muted uppercase tracking-wider">Restaurant Scoped</span>
            <Store className="w-4 h-4 text-emerald-500" />
          </div>
          <p className="text-lg font-black text-emerald-600 mt-1">
            {restaurantCoupons.length} <span className="text-xs font-normal text-text-muted">outlets</span>
          </p>
        </div>

        <div className="p-3.5 rounded-2xl bg-card border border-border shadow-2xs">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-bold text-text-muted uppercase tracking-wider">Redemptions</span>
            <Sparkles className="w-4 h-4 text-amber-500" />
          </div>
          <p className="text-lg font-black text-text-primary mt-1">
            {coupons.reduce((sum, c) => sum + (c.usedCount || 0), 0)}
          </p>
        </div>
      </div>

      {/* Visual Campaign Creator Form with Live Mobile Mockup */}
      {showAddCoupon && (
        <form
          onSubmit={handleCreateCoupon}
          className="bg-card border-2 border-orange-500/30 dark:border-orange-500/20 rounded-3xl p-5 sm:p-7 shadow-lg space-y-6 animate-slide-up relative overflow-hidden"
        >
          {/* Header banner inside creator */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-border/60 pb-4">
            <div>
              <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-orange-500/10 text-orange-600 text-[10px] font-black uppercase tracking-wider mb-1">
                <Sparkles className="w-3 h-3" /> Step-by-Step Campaign Builder
              </span>
              <h4 className="font-black text-text-primary text-base sm:text-lg">
                New Promotion Campaign
              </h4>
              <p className="text-xs text-text-secondary mt-0.5">
                Target grocery mart or specific restaurants with auto-applied BOGO &amp; free gifts
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            {/* Left: Configuration Inputs (7 cols) */}
            <div className="lg:col-span-7 space-y-5">
              {/* STEP 1: Target Destination */}
              <div>
                <label className="text-xs font-black text-text-primary block mb-2">
                  1. Target Audience / Outlet
                </label>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                  <button
                    type="button"
                    onClick={() => setNewCoupon({ ...newCoupon, restaurantId: '' })}
                    className={cn(
                      "p-3 rounded-2xl border text-left transition-all cursor-pointer",
                      !newCoupon.restaurantId
                        ? "border-primary bg-primary/5 shadow-xs ring-1 ring-primary/30"
                        : "border-border hover:border-border/80 bg-muted/10"
                    )}
                  >
                    <div className="flex items-center gap-2">
                      <div className="w-7 h-7 rounded-xl bg-primary/10 flex items-center justify-center text-primary font-black">
                        🛒
                      </div>
                      <div>
                        <h5 className="text-xs font-black text-text-primary">FastKirana Mart</h5>
                        <p className="text-[10px] text-text-secondary">Grocery Darkstore / All Users</p>
                      </div>
                    </div>
                  </button>

                  <div className="space-y-1">
                    <select
                      value={newCoupon.restaurantId || ''}
                      onChange={(e) => setNewCoupon({ ...newCoupon, restaurantId: e.target.value })}
                      className={cn(
                        "w-full px-3 py-3 text-xs rounded-2xl border bg-muted/10 focus:outline-none font-bold transition-all",
                        newCoupon.restaurantId
                          ? "border-orange-500 bg-orange-500/5 ring-1 ring-orange-500/30"
                          : "border-border"
                      )}
                    >
                      <option value="">🍽️ Choose Specific Restaurant...</option>
                      {restaurants.map((rest) => (
                        <option key={rest.id} value={rest.id}>
                          {rest.name}
                        </option>
                      ))}
                    </select>
                    {newCoupon.restaurantId && (
                      <div className="space-y-1 pt-1">
                        <span className="text-[10px] font-bold text-orange-600 block px-1">
                          ✓ Scoped to {selectedRestaurant?.name}
                        </span>
                        <div className="pt-1">
                          <label className="text-[10px] font-bold text-text-secondary block mb-1">
                            Restricted Menu Tag / Section (Optional)
                          </label>
                          <select
                            value={newCoupon.menuSection || ''}
                            onChange={(e) => setNewCoupon({ ...newCoupon, menuSection: e.target.value })}
                            className="w-full px-3 py-2 text-xs rounded-xl border bg-background font-semibold"
                          >
                            <option value="">All Menu Sections (Whole Restaurant)</option>
                            {getRestaurantMenuSections(selectedRestaurant).map((sec: any) => (
                              <option key={sec.tag} value={sec.tag}>
                                {sec.title} ({sec.tag})
                              </option>
                            ))}
                            <option value="pizza">Pizza (pizza)</option>
                            <option value="burger">Burger (burger)</option>
                            <option value="sandwich">Sandwich (sandwich)</option>
                            <option value="pasta">Pasta (pasta)</option>
                            <option value="beverages">Beverages (beverages)</option>
                          </select>
                          <span className="text-[9.5px] text-text-muted px-1 block">
                            Offer and badges will ONLY apply to dishes matching this menu section.
                          </span>
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* STEP 2: Campaign Type Cards */}
              <div>
                <label className="text-xs font-black text-text-primary block mb-2">
                  2. Campaign Discount Type
                </label>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                  {[
                    { type: 'BOGO', label: 'BOGO Gift', icon: '🔥', desc: 'Buy 1 Get 1 Free' },
                    { type: 'PERCENT', label: '% Percentage', icon: '💳', desc: 'e.g. 20% Off' },
                    { type: 'FLAT', label: '₹ Flat Off', icon: '🏷️', desc: 'e.g. ₹50 Off' },
                    { type: 'FREE_DELIVERY', label: 'Free Delivery', icon: '🚚', desc: 'Waive delivery fee' },
                  ].map((card) => {
                    const active = newCoupon.discountType === card.type
                    return (
                      <button
                        key={card.type}
                        type="button"
                        onClick={() => setNewCoupon({ ...newCoupon, discountType: card.type })}
                        className={cn(
                          "p-2.5 rounded-2xl border text-center transition-all cursor-pointer flex flex-col items-center justify-center gap-1",
                          active
                            ? "border-orange-500 bg-orange-500/10 shadow-xs ring-2 ring-orange-500/30"
                            : "border-border hover:border-border/80 bg-muted/10"
                        )}
                      >
                        <span className="text-xl">{card.icon}</span>
                        <span className="text-xs font-black text-text-primary">{card.label}</span>
                        <span className="text-[9px] text-text-muted">{card.desc}</span>
                      </button>
                    )
                  })}
                </div>
              </div>

              {/* BOGO Rules Sub-Section (If BOGO selected) */}
              {newCoupon.discountType === 'BOGO' && (
                <div className="bg-orange-500/5 border border-orange-500/20 rounded-2xl p-4 space-y-4 animate-slide-down">
                  <div className="flex items-center gap-2">
                    <Flame className="w-4 h-4 text-orange-500" />
                    <h5 className="text-xs font-black text-orange-700 dark:text-orange-400 uppercase tracking-wide">
                      BOGO Automation Rule
                    </h5>
                  </div>

                  {/* Subtype radio options */}
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
                    {[
                      {
                        key: 'BUY_LARGE_GET_SMALL',
                        title: 'Variant BOGO',
                        desc: 'Buy Large/Full, Get Small/Half Free',
                      },
                      {
                        key: 'SAME_ITEM',
                        title: 'Same Dish BOGO',
                        desc: 'Buy 1, get second of same dish at ₹0',
                      },
                      {
                        key: 'CHEAPEST_FREE',
                        title: 'Cheapest Free',
                        desc: 'Buy 2, lowest priced dish is 100% Free',
                      },
                    ].map((opt) => {
                      const sel = newCoupon.bogoType === opt.key
                      return (
                        <button
                          key={opt.key}
                          type="button"
                          onClick={() => setNewCoupon({ ...newCoupon, bogoType: opt.key })}
                          className={cn(
                            "p-2.5 rounded-xl border text-left transition-all cursor-pointer",
                            sel
                              ? "border-orange-500 bg-white dark:bg-zinc-900 shadow-xs ring-1 ring-orange-500/40"
                              : "border-border bg-background/50 hover:border-border/80"
                          )}
                        >
                          <span className="text-xs font-black text-text-primary block">{opt.title}</span>
                          <span className="text-[9.5px] text-text-secondary leading-tight block mt-0.5">
                            {opt.desc}
                          </span>
                        </button>
                      )
                    })}
                  </div>

                  {/* Variant match inputs if BUY_LARGE_GET_SMALL */}
                  {newCoupon.bogoType === 'BUY_LARGE_GET_SMALL' && (
                    <div className="grid grid-cols-2 gap-3 pt-1">
                      <div>
                        <label className="text-[10px] font-black text-text-secondary block mb-1">
                          Trigger Variant (Buy This)
                        </label>
                        <input
                          type="text"
                          placeholder="e.g. Large, Full"
                          value={newCoupon.triggerVariant || ''}
                          onChange={(e) => setNewCoupon({ ...newCoupon, triggerVariant: e.target.value })}
                          className="w-full px-3 py-2 text-xs rounded-xl border bg-background font-bold"
                        />
                      </div>
                      <div>
                        <label className="text-[10px] font-black text-text-secondary block mb-1">
                          Reward Variant (Get Free)
                        </label>
                        <input
                          type="text"
                          placeholder="e.g. Small, Half"
                          value={newCoupon.rewardVariant || ''}
                          onChange={(e) => setNewCoupon({ ...newCoupon, rewardVariant: e.target.value })}
                          className="w-full px-3 py-2 text-xs rounded-xl border bg-background font-bold"
                        />
                      </div>
                    </div>
                  )}

                  {/* Auto-apply checkbox */}
                  <div className="flex items-center gap-2 pt-1">
                    <input
                      type="checkbox"
                      id="bogoAutoApply"
                      checked={newCoupon.autoApply || false}
                      onChange={(e) => setNewCoupon({ ...newCoupon, autoApply: e.target.checked })}
                      className="h-4 w-4 text-orange-600 focus:ring-orange-500 border-border rounded cursor-pointer"
                    />
                    <label htmlFor="bogoAutoApply" className="text-xs font-bold text-text-primary cursor-pointer select-none">
                      ⚡ Auto-Apply at Checkout (Customer does not need to type coupon code)
                    </label>
                  </div>
                </div>
              )}

              {/* STEP 3: Coupon Code & Value details */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div>
                  <label className="text-[10px] font-black text-text-secondary block mb-1">
                    Coupon Code *
                  </label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. BOGOPIZZA, WEDSON50"
                    value={newCoupon.code}
                    onChange={(e) => setNewCoupon({ ...newCoupon, code: e.target.value.toUpperCase() })}
                    className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/15 focus:outline-none focus:border-primary font-black uppercase tracking-wider"
                  />
                </div>

                {newCoupon.discountType !== 'BOGO' && newCoupon.discountType !== 'FREE_DELIVERY' && (
                  <div>
                    <label className="text-[10px] font-black text-text-secondary block mb-1">
                      {newCoupon.discountType === 'PERCENT' ? 'Discount Percentage (%) *' : 'Discount Value (₹) *'}
                    </label>
                    <input
                      type="number"
                      step="0.01"
                      required
                      placeholder={newCoupon.discountType === 'PERCENT' ? 'e.g. 20' : 'e.g. 50'}
                      value={newCoupon.value}
                      onChange={(e) => setNewCoupon({ ...newCoupon, value: e.target.value })}
                      className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/15 focus:outline-none focus:border-primary font-bold"
                    />
                  </div>
                )}

                <div>
                  <label className="text-[10px] font-black text-text-secondary block mb-1">
                    Min Order Value (₹)
                  </label>
                  <input
                    type="number"
                    step="0.01"
                    placeholder="e.g. 199 (0 for none)"
                    value={newCoupon.minOrder}
                    onChange={(e) => setNewCoupon({ ...newCoupon, minOrder: e.target.value })}
                    className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/15 focus:outline-none focus:border-primary font-bold"
                  />
                </div>

                <div>
                  <label className="text-[10px] font-black text-text-secondary block mb-1">
                    Max Discount Cap (₹)
                  </label>
                  <input
                    type="number"
                    step="0.01"
                    placeholder="e.g. 100 (optional)"
                    value={newCoupon.maxDiscount}
                    onChange={(e) => setNewCoupon({ ...newCoupon, maxDiscount: e.target.value })}
                    className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/15 focus:outline-none focus:border-primary font-bold"
                  />
                </div>
              </div>

              {/* STEP 4: Storefront Ribbon Sync */}
              <div className="bg-muted/30 border border-border/80 rounded-2xl p-4 space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="text-base">🔥</span>
                    <div>
                      <h5 className="text-xs font-black text-text-primary">
                        Auto-Sync Promotional Ribbon
                      </h5>
                      <p className="text-[10px] text-text-secondary">
                        Display ribbon directly on Home Screen Restaurant Card &amp; Menu Header
                      </p>
                    </div>
                  </div>
                  <input
                    type="checkbox"
                    id="syncRibbon"
                    checked={newCoupon.syncRestaurantBadge !== false}
                    onChange={(e) => setNewCoupon({ ...newCoupon, syncRestaurantBadge: e.target.checked })}
                    className="h-4 w-4 text-orange-600 focus:ring-orange-500 border-border rounded cursor-pointer"
                  />
                </div>

                <div>
                  <label className="text-[10px] font-black text-text-secondary block mb-1">
                    Ribbon Badge Text
                  </label>
                  <input
                    type="text"
                    placeholder={autoGeneratedBadge}
                    value={newCoupon.badgeText || ''}
                    onChange={(e) => setNewCoupon({ ...newCoupon, badgeText: e.target.value })}
                    className="w-full px-3 py-2 text-xs rounded-xl border bg-background font-black tracking-wide"
                  />
                  <span className="text-[9.5px] text-text-muted mt-1 block">
                    Default: {autoGeneratedBadge}
                  </span>
                </div>
              </div>

              {/* Submit Buttons */}
              <div className="flex items-center gap-3 pt-2">
                <button
                  type="submit"
                  disabled={isCreatingCoupon}
                  className="flex-1 py-3 px-5 bg-gradient-to-r from-orange-600 to-red-600 hover:from-orange-700 hover:to-red-700 text-white text-xs font-black rounded-xl shadow-md transition-all active:scale-95 disabled:opacity-50 cursor-pointer flex items-center justify-center gap-2"
                >
                  {isCreatingCoupon ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      <span>Creating Campaign...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-4 w-4" />
                      <span>Launch Campaign Live</span>
                    </>
                  )}
                </button>
                <button
                  type="button"
                  onClick={() => setShowAddCoupon(false)}
                  className="px-4 py-3 border border-border rounded-xl text-xs font-bold hover:bg-muted transition-colors cursor-pointer"
                >
                  Cancel
                </button>
              </div>
            </div>

            {/* Right: Live Customer Phone Mockup Preview (5 cols) */}
            <div className="lg:col-span-5 flex flex-col items-center">
              <div className="w-full max-w-[320px] bg-zinc-950 text-white rounded-[38px] p-3 shadow-2xl border-4 border-zinc-800 relative">
                {/* Phone Notch & Speaker */}
                <div className="flex justify-center mb-2">
                  <div className="w-20 h-4 bg-zinc-800 rounded-full flex items-center justify-center">
                    <div className="w-2.5 h-2.5 rounded-full bg-zinc-700 mr-2" />
                    <div className="w-8 h-1 rounded-full bg-zinc-700" />
                  </div>
                </div>

                {/* Preview Navigation Tabs */}
                <div className="flex items-center justify-around bg-zinc-900 rounded-xl p-1 mb-3 text-[10px] font-black">
                  <button
                    type="button"
                    onClick={() => setPreviewTab('card')}
                    className={cn(
                      "px-2.5 py-1 rounded-lg text-xs font-bold transition-all",
                      previewTab === 'card' 
                        ? "bg-orange-600 text-white shadow-xs" 
                        : "text-zinc-500 hover:text-zinc-300"
                    )}
                  >
                    1. Home Card
                  </button>
                  <button
                    type="button"
                    onClick={() => setPreviewTab('menu')}
                    className={cn(
                      "px-2.5 py-1 rounded-lg text-xs font-bold transition-all",
                      previewTab === 'menu' 
                        ? "bg-orange-600 text-white shadow-xs" 
                        : "text-zinc-500 hover:text-zinc-300"
                    )}
                  >
                    2. Menu Ticket
                  </button>
                  <button
                    type="button"
                    onClick={() => setPreviewTab('cart')}
                    className={cn(
                      "px-2.5 py-1 rounded-lg text-xs font-bold transition-all",
                      previewTab === 'cart' 
                        ? "bg-orange-600 text-white shadow-xs" 
                        : "text-zinc-500 hover:text-zinc-300"
                    )}
                  >
                    3. Cart Gift
                  </button>
                </div>

                {/* Live Preview Screen Content */}
                <div className="bg-zinc-900/90 rounded-2xl p-3 min-h-[300px] flex flex-col justify-center border border-zinc-800">
                  {/* VIEW 1: Home Screen Restaurant Card Preview */}
                  {previewTab === 'card' && (
                    <div className="space-y-2">
                      <span className="text-[9px] font-bold text-zinc-400 uppercase tracking-wider block text-center">
                        Home Screen Live Ribbon
                      </span>
                      <div className="bg-white text-zinc-900 rounded-xl p-2.5 shadow-md space-y-2">
                        <div className="relative h-24 bg-gradient-to-br from-orange-400 to-red-500 rounded-lg overflow-hidden flex items-end p-2">
                          <div className="absolute top-1.5 right-1.5 px-2 py-0.5 rounded-md bg-black/60 text-white text-[8px] font-black">
                            30-40 min
                          </div>
                          {/* Live Ribbon */}
                          <div className="bg-gradient-to-r from-orange-600 to-red-600 text-white px-2 py-0.5 rounded text-[8.5px] font-black shadow-md flex items-center gap-1">
                            <span>🔥</span>
                            <span>{effectiveBadge}</span>
                          </div>
                        </div>
                        <div>
                          <h6 className="text-xs font-black truncate">
                            {selectedRestaurant?.name || 'A.S Restaurant & Cafe'}
                          </h6>
                          <p className="text-[9px] text-zinc-500 truncate">
                            North Indian, Fast Food, Pizzas
                          </p>
                        </div>
                      </div>
                    </div>
                  )}

                  {/* VIEW 2: Menu Swipeable Ticket Preview */}
                  {previewTab === 'menu' && (
                    <div className="space-y-2">
                      <span className="text-[9px] font-bold text-zinc-400 uppercase tracking-wider block text-center">
                        Menu Header Ticket Notch
                      </span>
                      <div className="relative bg-gradient-to-br from-amber-500/20 via-orange-500/10 to-red-500/20 border border-orange-500/30 rounded-xl p-3 text-white space-y-1.5 overflow-hidden">
                        <div className="flex items-center justify-between">
                          <span className="px-2 py-0.5 rounded-full bg-orange-600 text-[8px] font-black uppercase tracking-wider">
                            {newCoupon.discountType === 'BOGO' ? 'BOGO DEAL' : 'SPECIAL OFFER'}
                          </span>
                          <span className="font-mono text-[9px] font-black text-orange-400 bg-orange-500/10 px-1.5 py-0.5 rounded">
                            {newCoupon.code || 'COUPONCODE'}
                          </span>
                        </div>
                        <h6 className="text-xs font-black text-orange-300">
                          {effectiveBadge}
                        </h6>
                        <p className="text-[9px] text-zinc-300">
                          {newCoupon.minOrder ? `Above ₹${newCoupon.minOrder}` : 'No minimum order'}
                        </p>
                        <button
                          type="button"
                          className="w-full py-1 rounded bg-orange-600 hover:bg-orange-500 text-white text-[9px] font-black uppercase mt-1 cursor-pointer"
                        >
                          TAP TO APPLY
                        </button>
                      </div>
                    </div>
                  )}

                  {/* VIEW 3: Cart Auto-dropped Gift Preview */}
                  {previewTab === 'cart' && (
                    <div className="space-y-2">
                      <span className="text-[9px] font-bold text-zinc-400 uppercase tracking-wider block text-center">
                        Cart Free Gift Auto-Drop
                      </span>
                      <div className="bg-emerald-950/60 border border-emerald-500/40 rounded-xl p-2.5 text-white space-y-1.5">
                        <div className="flex items-center justify-between">
                          <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full bg-emerald-600 text-[8px] font-black uppercase">
                            <Gift className="w-2.5 h-2.5" /> 100% Free Gift
                          </span>
                          <span className="text-[8px] font-bold text-emerald-400">
                            Saved ₹129!
                          </span>
                        </div>
                        <div className="flex items-center gap-2">
                          <div className="w-9 h-9 rounded-lg bg-zinc-800 flex items-center justify-center text-lg">
                            🍕
                          </div>
                          <div className="flex-1 min-w-0">
                            <h6 className="text-[10px] font-black truncate">
                              Small Cheese Pizza
                            </h6>
                            <div className="flex items-center gap-1.5">
                              <span className="text-[9px] text-zinc-400 line-through">₹129</span>
                              <span className="text-[10px] font-black text-emerald-400">FREE</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  )}
                </div>

                <p className="text-[9px] text-zinc-500 text-center mt-2">
                  Works identically on Web &amp; Flutter Mobile
                </p>
              </div>
            </div>
          </div>
        </form>
      )}

      {/* Coupons List */}
      <div className="bg-card border border-border rounded-2xl p-6 shadow-sm overflow-hidden">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="font-extrabold text-text-primary text-base">Active Campaigns & Coupons</h3>
            <p className="text-xs text-text-secondary">Track store-wide coupons and restaurant-specific BOGO promotions</p>
          </div>
          <span className="text-xs font-bold text-text-secondary bg-muted px-2.5 py-1 rounded-lg border border-border">
            {coupons.length} total
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-xs">
            <thead>
              <tr className="border-b border-border text-text-secondary uppercase tracking-wider font-bold">
                <th className="py-3 px-4">Campaign & Code</th>
                <th className="py-3 px-4">Outlet / Target</th>
                <th className="py-3 px-4">Deal Structure</th>
                <th className="py-3 px-4">Min Order</th>
                <th className="py-3 px-4">Max Cap</th>
                <th className="py-3 px-4 text-center">Usage</th>
                <th className="py-3 px-4 text-center">Status</th>
                <th className="py-3 px-4">Expires</th>
                <th className="py-3 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/40 font-semibold">
              {isLoadingCoupons ? (
                <tr>
                  <td colSpan={9} className="text-center py-10 text-text-secondary">
                    <Loader2 className="h-8 w-8 animate-spin mx-auto mb-2 text-primary" />
                    Loading coupons...
                  </td>
                </tr>
              ) : coupons.length === 0 ? (
                <tr>
                  <td colSpan={9} className="text-center py-10 text-text-secondary">
                    <Ticket className="h-8 w-8 mx-auto mb-2 text-text-muted" />
                    No coupons created yet.
                  </td>
                </tr>
              ) : (
                coupons.map((c) => {
                  const isExpired = c.expiresAt && new Date(c.expiresAt) < new Date()
                  const targetRest = c.restaurant?.name || restaurants.find((r) => r.id === c.restaurantId)?.name

                  return (
                    <tr key={c.id} className={`hover:bg-muted/30 ${isExpired ? 'opacity-60' : ''}`}>
                      {/* Campaign & Code */}
                      <td className="py-3 px-4">
                        <div className="flex flex-col gap-1">
                          <span className="font-mono font-black text-[11px] bg-purple-500/10 text-purple-600 dark:text-purple-400 px-2 py-0.5 rounded-lg border border-purple-500/20 w-fit">
                            {c.code}
                          </span>
                          {c.badgeText && (
                            <span className="text-[10px] font-extrabold text-orange-600 dark:text-orange-400 flex items-center gap-1">
                              <Flame className="h-3 w-3 inline text-orange-500" />
                              {c.badgeText}
                            </span>
                          )}
                        </div>
                      </td>

                      {/* Outlet / Target */}
                      <td className="py-3 px-4">
                        {targetRest ? (
                          <div className="flex items-center gap-1 text-[11px] font-bold text-amber-600 dark:text-amber-400 bg-amber-500/10 px-2 py-0.5 rounded-md border border-amber-500/20 w-fit">
                            <Store className="h-3 w-3" />
                            {targetRest}
                          </div>
                        ) : (
                          <span className="text-[11px] text-text-secondary font-medium">
                            🛒 All Grocery
                          </span>
                        )}
                      </td>

                      {/* Deal Structure */}
                      <td className="py-3 px-4">
                        {c.discountType === 'BOGO' ? (
                          <div className="space-y-0.5">
                            <div className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-black bg-orange-500/15 text-orange-600 dark:text-orange-400 border border-orange-500/30">
                              <Gift className="h-3 w-3" />
                              BOGO DEAL
                            </div>
                            <div className="text-[11px] font-bold text-text-primary">
                              {c.bogoType === 'BUY_LARGE_GET_SMALL'
                                ? `Buy ${c.triggerVariant || 'Large'} ➔ ${c.rewardVariant || 'Small'} FREE`
                                : c.bogoType === 'SAME_ITEM'
                                ? 'Buy 1 Get Same 1 FREE'
                                : 'Buy 2+, Cheapest Item FREE'}
                            </div>
                            {c.autoApply && (
                              <span className="inline-block text-[9px] font-bold text-emerald-600 dark:text-emerald-400">
                                ⚡ Auto-Applies in Cart
                              </span>
                            )}
                          </div>
                        ) : c.discountType === 'FREE_DELIVERY' ? (
                          <div className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[11px] font-bold bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border border-emerald-500/30">
                            <Truck className="h-3 w-3" /> Free Delivery
                          </div>
                        ) : (
                          <div className="flex items-center gap-1 text-[12px] font-black text-accent">
                            {c.discountType === 'PERCENT' ? (
                              <><Percent className="h-3 w-3 text-blue-500" /> {c.value}% OFF</>
                            ) : (
                              <><IndianRupee className="h-3 w-3 text-emerald-500" /> ₹{c.value} FLAT</>
                            )}
                          </div>
                        )}
                      </td>

                      {/* Min Order */}
                      <td className="py-3 px-4">
                        <span className="text-text-secondary">{Number(c.minOrder) > 0 ? `₹${c.minOrder}` : 'No min'}</span>
                      </td>

                      {/* Max Discount */}
                      <td className="py-3 px-4">
                        <span className="text-text-secondary">
                          {c.maxDiscount ? `₹${c.maxDiscount}` : '—'}
                        </span>
                      </td>

                      {/* Usage */}
                      <td className="py-3 px-4 text-center">
                        <span className="bg-muted px-2 py-0.5 rounded border text-[10px] font-bold">
                          {c.usedCount}{c.maxUses ? ` / ${c.maxUses}` : ' / ∞'}
                        </span>
                      </td>

                      {/* Status */}
                      <td className="py-3 px-4 text-center">
                        <button
                          onClick={() => handleToggleCoupon(c.id, c.isActive)}
                          disabled={savingCouponId === c.id}
                          className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[9px] font-bold cursor-pointer transition-all ${
                            c.isActive
                              ? 'bg-accent/15 text-accent border border-accent/20 hover:bg-accent/25'
                              : 'bg-muted text-text-muted border border-border hover:bg-muted/80'
                          }`}
                        >
                          {savingCouponId === c.id ? (
                            <Loader2 className="h-3 w-3 animate-spin" />
                          ) : c.isActive ? (
                            <ToggleRight className="h-3 w-3" />
                          ) : (
                            <ToggleLeft className="h-3 w-3" />
                          )}
                          {c.isActive ? 'Active' : 'Disabled'}
                        </button>
                      </td>

                      {/* Expires */}
                      <td className="py-3 px-4">
                        <span className={`text-[10px] font-medium ${isExpired ? 'text-discount font-bold' : 'text-text-muted'}`}>
                          {c.expiresAt
                            ? formatDate(c.expiresAt, 'd MMM yyyy')
                            : 'Never'}
                          {isExpired && ' (Expired)'}
                        </span>
                      </td>

                      {/* Actions */}
                      <td className="py-3 px-4 text-right">
                        <div className="flex items-center justify-end gap-1.5">
                          <button
                            onClick={() => startEditingCoupon(c)}
                            className="p-1.5 border border-border hover:bg-muted text-text-secondary rounded-lg transition-colors"
                            title="Edit coupon"
                          >
                            <Pencil className="h-3.5 w-3.5" />
                          </button>
                          <button
                            onClick={() => handleDeleteCoupon(c.id)}
                            disabled={deletingCouponId === c.id}
                            className="p-1.5 border border-border text-discount hover:bg-discount/10 hover:border-discount/20 rounded-lg transition-colors"
                            title="Delete coupon"
                          >
                            {deletingCouponId === c.id ? (
                              <Loader2 className="h-3.5 w-3.5 animate-spin" />
                            ) : (
                              <Trash2 className="h-3.5 w-3.5" />
                            )}
                          </button>
                        </div>
                      </td>
                    </tr>
                  )
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Edit Coupon Modal */}
      {editingCoupon && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm animate-fade-in p-4 overflow-y-auto">
          <div className="bg-card border border-border rounded-2xl shadow-xl w-full max-w-xl p-6 animate-scale-up space-y-4 my-8 max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-center border-b border-border/60 pb-3">
              <div>
                <h4 className="font-extrabold text-text-primary text-base">Edit Promotion &amp; Coupon</h4>
                <p className="text-xs text-text-secondary">Modify campaign rules, BOGO items or restaurant scoping</p>
              </div>
              <button onClick={() => setEditingCoupon(null)} className="text-text-secondary hover:text-text-primary">
                <X className="h-5 w-5" />
              </button>
            </div>
            <form onSubmit={saveCouponChanges} className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Coupon Code */}
                <div>
                  <label className="text-[10px] font-bold text-text-secondary block mb-1">Coupon Code *</label>
                  <input
                    type="text"
                    required
                    value={couponEditForm.code}
                    onChange={(e) => setCouponEditForm({ ...couponEditForm, code: e.target.value.toUpperCase() })}
                    className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/20 focus:outline-none focus:border-primary font-mono font-black uppercase tracking-wider"
                  />
                </div>

                {/* Target Restaurant */}
                <div>
                  <label className="text-[10px] font-bold text-text-secondary block mb-1">Target Outlet / Destination</label>
                  <select
                    value={couponEditForm.restaurantId || ''}
                    onChange={(e) => setCouponEditForm({ ...couponEditForm, restaurantId: e.target.value })}
                    className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/20 focus:outline-none focus:border-primary font-semibold"
                  >
                    <option value="">🛒 Grocery Mart (Universal)</option>
                    {restaurants.map((rest) => (
                      <option key={rest.id} value={rest.id}>
                        🏪 Restaurant: {rest.name}
                      </option>
                    ))}
                  </select>
                </div>

                {/* Discount Type */}
                <div>
                  <label className="text-[10px] font-bold text-text-secondary block mb-1">Campaign Type *</label>
                  <select
                    value={couponEditForm.discountType}
                    onChange={(e) => setCouponEditForm({ ...couponEditForm, discountType: e.target.value })}
                    className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/20 focus:outline-none focus:border-primary font-semibold"
                  >
                    <option value="BOGO">🔥 BOGO (Buy 1 Get 1 Free)</option>
                    <option value="PERCENT">Percentage (%) Discount</option>
                    <option value="FLAT">Flat Amount (₹) Off</option>
                    <option value="FREE_DELIVERY">🚚 100% Free Delivery</option>
                  </select>
                </div>

                {/* Discount Value (if not BOGO / Free Delivery) */}
                {couponEditForm.discountType !== 'BOGO' && couponEditForm.discountType !== 'FREE_DELIVERY' && (
                  <div>
                    <label className="text-[10px] font-bold text-text-secondary block mb-1">
                      Discount Value * {couponEditForm.discountType === 'PERCENT' ? '(%)' : '(₹)'}
                    </label>
                    <input
                      type="number"
                      step="0.01"
                      required
                      value={couponEditForm.value}
                      onChange={(e) => setCouponEditForm({ ...couponEditForm, value: e.target.value })}
                      className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/20 focus:outline-none focus:border-primary font-semibold"
                    />
                  </div>
                )}

                {/* BOGO Fields */}
                {couponEditForm.discountType === 'BOGO' && (
                  <>
                    <div className="md:col-span-2 p-3.5 rounded-xl bg-orange-500/10 border border-orange-500/20 space-y-3">
                      <div>
                        <label className="text-[10px] font-black text-orange-600 dark:text-orange-400 uppercase tracking-wider block mb-1">
                          BOGO Sub-Rule
                        </label>
                        <select
                          value={couponEditForm.bogoType || 'BUY_LARGE_GET_SMALL'}
                          onChange={(e) => setCouponEditForm({ ...couponEditForm, bogoType: e.target.value })}
                          className="w-full px-3 py-2 text-xs rounded-lg border bg-background font-bold text-text-primary"
                        >
                          <option value="BUY_LARGE_GET_SMALL">Buy Large/Medium ➔ Get Small 100% Free</option>
                          <option value="SAME_ITEM">Buy 1 ➔ Get Exactly Same Item Free</option>
                          <option value="CHEAPEST_FREE">Buy 2 or more ➔ Get Cheapest Item Free</option>
                        </select>
                      </div>

                      {couponEditForm.bogoType === 'BUY_LARGE_GET_SMALL' && (
                        <div className="grid grid-cols-2 gap-3 pt-1">
                          <div>
                            <label className="text-[10px] font-bold text-text-secondary block mb-1">Trigger Size Keyword</label>
                            <input
                              type="text"
                              value={couponEditForm.triggerVariant || 'Large'}
                              onChange={(e) => setCouponEditForm({ ...couponEditForm, triggerVariant: e.target.value })}
                              placeholder="e.g. Large, Medium"
                              className="w-full px-3 py-1.5 text-xs rounded-lg border bg-background font-semibold"
                            />
                          </div>
                          <div>
                            <label className="text-[10px] font-bold text-text-secondary block mb-1">Free Gift Size Keyword</label>
                            <input
                              type="text"
                              value={couponEditForm.rewardVariant || 'Small'}
                              onChange={(e) => setCouponEditForm({ ...couponEditForm, rewardVariant: e.target.value })}
                              placeholder="e.g. Small, Regular"
                              className="w-full px-3 py-1.5 text-xs rounded-lg border bg-background font-semibold"
                            />
                          </div>
                        </div>
                      )}

                      <div className="flex items-center gap-2 pt-1">
                        <input
                          type="checkbox"
                          id="editAutoApply"
                          checked={couponEditForm.autoApply ?? false}
                          onChange={(e) => setCouponEditForm({ ...couponEditForm, autoApply: e.target.checked })}
                          className="h-4 w-4 text-orange-500 rounded border-border"
                        />
                        <label htmlFor="editAutoApply" className="text-xs font-bold text-text-primary cursor-pointer">
                          ⚡ Auto-apply in cart when customer adds qualifying items
                        </label>
                      </div>
                    </div>
                  </>
                )}

                {/* Badge Text */}
                <div className="md:col-span-2">
                  <label className="text-[10px] font-bold text-text-secondary block mb-1">
                    Display Ribbon / Badge Text (Appears on Card &amp; Menu)
                  </label>
                  <input
                    type="text"
                    value={couponEditForm.badgeText || ''}
                    onChange={(e) => setCouponEditForm({ ...couponEditForm, badgeText: e.target.value })}
                    placeholder="e.g. BUY 1 GET 1 FREE"
                    className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/20 focus:outline-none focus:border-primary font-bold"
                  />
                </div>

                {/* Min Order */}
                <div>
                  <label className="text-[10px] font-bold text-text-secondary block mb-1">Min Order Value (₹)</label>
                  <input
                    type="number"
                    step="0.01"
                    value={couponEditForm.minOrder}
                    onChange={(e) => setCouponEditForm({ ...couponEditForm, minOrder: e.target.value })}
                    className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/20 focus:outline-none focus:border-primary font-semibold"
                  />
                </div>

                {/* Max Cap */}
                <div>
                  <label className="text-[10px] font-bold text-text-secondary block mb-1">Max Discount Cap (₹)</label>
                  <input
                    type="number"
                    step="0.01"
                    value={couponEditForm.maxDiscount}
                    onChange={(e) => setCouponEditForm({ ...couponEditForm, maxDiscount: e.target.value })}
                    className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/20 focus:outline-none focus:border-primary font-semibold"
                    placeholder="Unlimited"
                  />
                </div>

                {/* Max Total Uses */}
                <div>
                  <label className="text-[10px] font-bold text-text-secondary block mb-1">Max Total Uses</label>
                  <input
                    type="number"
                    value={couponEditForm.maxUses}
                    onChange={(e) => setCouponEditForm({ ...couponEditForm, maxUses: e.target.value })}
                    className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/20 focus:outline-none focus:border-primary font-semibold"
                    placeholder="Unlimited"
                  />
                </div>

                {/* Expiry Date */}
                <div>
                  <label className="text-[10px] font-bold text-text-secondary block mb-1">Expiry Date</label>
                  <input
                    type="date"
                    value={couponEditForm.expiresAt}
                    onChange={(e) => setCouponEditForm({ ...couponEditForm, expiresAt: e.target.value })}
                    className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/20 focus:outline-none focus:border-primary font-semibold"
                  />
                </div>

                {/* Restrict Category */}
                <div>
                  <label className="text-[10px] font-bold text-text-secondary block mb-1">Restricted Category (Optional)</label>
                  <select
                    value={couponEditForm.categoryId}
                    onChange={(e) => setCouponEditForm({ ...couponEditForm, categoryId: e.target.value })}
                    className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/20 focus:outline-none focus:border-primary font-semibold"
                  >
                    <option value="">All Categories (No restriction)</option>
                    {categories.map((cat) => (
                      <option key={cat.id} value={cat.id}>{cat.name}</option>
                    ))}
                  </select>
                </div>

                {/* Restricted Restaurant Menu Tag / Section */}
                {couponEditForm.restaurantId && (
                  <div>
                    <label className="text-[10px] font-bold text-text-secondary block mb-1">
                      Restricted Menu Tag / Section (Optional)
                    </label>
                    <select
                      value={couponEditForm.menuSection || ''}
                      onChange={(e) => setCouponEditForm({ ...couponEditForm, menuSection: e.target.value })}
                      className="w-full px-3 py-2 text-xs rounded-xl border bg-muted/20 focus:outline-none focus:border-primary font-semibold"
                    >
                      <option value="">All Menu Sections (No restriction)</option>
                      {getRestaurantMenuSections(restaurants.find((r) => r.id === couponEditForm.restaurantId)).map((sec: any) => (
                        <option key={sec.tag} value={sec.tag}>
                          {sec.title} ({sec.tag})
                        </option>
                      ))}
                      <option value="pizza">Pizza (pizza)</option>
                      <option value="burger">Burger (burger)</option>
                      <option value="sandwich">Sandwich (sandwich)</option>
                      <option value="pasta">Pasta (pasta)</option>
                      <option value="beverages">Beverages (beverages)</option>
                    </select>
                    <span className="text-[9.5px] text-text-muted mt-0.5 block">
                      Offer &amp; badges will only apply to dishes matching this menu tag.
                    </span>
                  </div>
                )}

                {/* Restaurant Sync Ribbon Toggle */}
                {couponEditForm.restaurantId && (
                  <div className="md:col-span-2 p-2.5 rounded-xl bg-muted/40 border border-border flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="editSyncBadge"
                      checked={couponEditForm.syncRestaurantBadge ?? true}
                      onChange={(e) => setCouponEditForm({ ...couponEditForm, syncRestaurantBadge: e.target.checked })}
                      className="h-4 w-4 text-accent rounded border-border"
                    />
                    <label htmlFor="editSyncBadge" className="text-xs font-bold text-text-primary cursor-pointer select-none">
                      Sync ribbon banner to Restaurant Card on Home &amp; Discovery screens
                    </label>
                  </div>
                )}

                {/* Checkbox settings */}
                <div className="md:col-span-2 flex flex-wrap gap-4 pt-1">
                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="editCouponActive"
                      checked={couponEditForm.isActive}
                      onChange={(e) => setCouponEditForm({ ...couponEditForm, isActive: e.target.checked })}
                      className="h-4 w-4 text-primary focus:ring-primary border-border rounded cursor-pointer"
                    />
                    <label htmlFor="editCouponActive" className="text-xs font-bold text-text-primary cursor-pointer select-none">
                      Coupon is Active
                    </label>
                  </div>
                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="editOncePerCustomer"
                      checked={couponEditForm.oncePerCustomer}
                      onChange={(e) => setCouponEditForm({ ...couponEditForm, oncePerCustomer: e.target.checked })}
                      className="h-4 w-4 text-primary focus:ring-primary border-border rounded cursor-pointer"
                    />
                    <label htmlFor="editOncePerCustomer" className="text-xs font-bold text-text-primary cursor-pointer select-none">
                      Limit to once per customer
                    </label>
                  </div>
                </div>
              </div>

              <div className="flex justify-end gap-2 border-t border-border/40 pt-4">
                <button
                  type="button"
                  onClick={() => setEditingCoupon(null)}
                  className="px-4 py-2 border rounded-xl text-xs font-bold hover:bg-muted/50 transition-all"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={savingCouponId === editingCoupon.id}
                  className="flex items-center gap-1 px-5 py-2 bg-accent text-white text-xs font-bold rounded-xl hover:bg-accent/90 transition-all shadow-sm disabled:opacity-50"
                >
                  {savingCouponId === editingCoupon.id ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Saving...
                    </>
                  ) : (
                    'Save Changes'
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}
