// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQWQfnvR5gb97DnXMgB0Cvp30g7W3TLrg',
    appId: '1:538637022333:web:5042cb3a9ffaa90a8bed14',
    messagingSenderId: '538637022333',
    projectId: 'fastkirana-98a68',
    authDomain: 'fastkirana-98a68.firebaseapp.com',
    storageBucket: 'fastkirana-98a68.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQWQfnvR5gb97DnXMgB0Cvp30g7W3TLrg',
    appId: '1:538637022333:android:c802bb4fe04d8eaa8bed14',
    messagingSenderId: '538637022333',
    projectId: 'fastkirana-98a68',
    storageBucket: 'fastkirana-98a68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQWQfnvR5gb97DnXMgB0Cvp30g7W3TLrg',
    appId: '1:538637022333:ios:c802bb4fe04d8eaa8bed14',
    messagingSenderId: '538637022333',
    projectId: 'fastkirana-98a68',
    storageBucket: 'fastkirana-98a68.firebasestorage.app',
    iosBundleId: 'com.fastkirana.app',
  );
}
